//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Alterar.
        /// </summary>
        internal static string Alterar {
            get {
                return ResourceManager.GetString("Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Atenção!.
        /// </summary>
        internal static string Atencao {
            get {
                return ResourceManager.GetString("Atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ativo.
        /// </summary>
        internal static string Ativo {
            get {
                return ResourceManager.GetString("Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Celula.
        /// </summary>
        internal static string Celula {
            get {
                return ResourceManager.GetString("Celula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Detalhes.
        /// </summary>
        internal static string Detalhes {
            get {
                return ResourceManager.GetString("Detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Preencha um E-mail válido.
        /// </summary>
        internal static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Erro!.
        /// </summary>
        internal static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Falha na operação!.
        /// </summary>
        internal static string FalhaOperacao {
            get {
                return ResourceManager.GetString("FalhaOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Há {0} alertas:.
        /// </summary>
        internal static string ListaAtencao {
            get {
                return ResourceManager.GetString("ListaAtencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Há {0} erros:.
        /// </summary>
        internal static string ListaErro {
            get {
                return ResourceManager.GetString("ListaErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Há {0} notificações:.
        /// </summary>
        internal static string ListaInfo {
            get {
                return ResourceManager.GetString("ListaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Há {0} notificações de sucesso:.
        /// </summary>
        internal static string ListaSucesso {
            get {
                return ResourceManager.GetString("ListaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Máximo {0} caracteres.
        /// </summary>
        internal static string MaximoCaracteres {
            get {
                return ResourceManager.GetString("MaximoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Mínimo {0} caracteres.
        /// </summary>
        internal static string MinimoCaracteres {
            get {
                return ResourceManager.GetString("MinimoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nenhum registro encontrado.
        /// </summary>
        internal static string NenhumRegistroEncontrado {
            get {
                return ResourceManager.GetString("NenhumRegistroEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Noto Item.
        /// </summary>
        internal static string NovoItem {
            get {
                return ResourceManager.GetString("NovoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Registro alterado!.
        /// </summary>
        internal static string RegistroAlterado {
            get {
                return ResourceManager.GetString("RegistroAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a &lt;b&gt;{0}&lt;/b&gt; registro encontrado em &lt;b&gt;{1}&lt;/b&gt; página.
        /// </summary>
        internal static string RegistroEncontrado1 {
            get {
                return ResourceManager.GetString("RegistroEncontrado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a &lt;b&gt;{0}&lt;/b&gt; registros encontrados em &lt;b&gt;{1}&lt;/b&gt; página.
        /// </summary>
        internal static string RegistroEncontrado2 {
            get {
                return ResourceManager.GetString("RegistroEncontrado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a &lt;b&gt;{0}&lt;/b&gt; registros encontrados em &lt;b&gt;{1}&lt;/b&gt; páginas.
        /// </summary>
        internal static string RegistroEncontrado3 {
            get {
                return ResourceManager.GetString("RegistroEncontrado3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Registro excluído!.
        /// </summary>
        internal static string RegistroExcluido {
            get {
                return ResourceManager.GetString("RegistroExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Registro incluído!.
        /// </summary>
        internal static string RegistroIncluido {
            get {
                return ResourceManager.GetString("RegistroIncluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sucesso!.
        /// </summary>
        internal static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Preencha o campo E-mail.
        /// </summary>
        internal static string VSEmail {
            get {
                return ResourceManager.GetString("VSEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Preencha o campo Login.
        /// </summary>
        internal static string VSLogin {
            get {
                return ResourceManager.GetString("VSLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Preencha o campo Nome.
        /// </summary>
        internal static string VSNome {
            get {
                return ResourceManager.GetString("VSNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Preencha o campo Senha.
        /// </summary>
        internal static string VSSenha {
            get {
                return ResourceManager.GetString("VSSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Preencha o campo Sobrenome.
        /// </summary>
        internal static string VSSobrenome {
            get {
                return ResourceManager.GetString("VSSobrenome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Preencha o campo Telefone.
        /// </summary>
        internal static string VSTelefone {
            get {
                return ResourceManager.GetString("VSTelefone", resourceCulture);
            }
        }
    }
}
